
// Objective-C API for talking to the following Go packages
//
//	github.com/akovardin/pong/pongmobile
//	github.com/hajimehoshi/ebiten/v2/mobile/ebitenmobileview
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Pong_FRAMEWORK_H__
#define __Pong_FRAMEWORK_H__

#include "Pongmobile.objc.h"
#include "Ebitenmobileview.objc.h"
#include "Universe.objc.h"

#endif
