// Objective-C API for talking to github.com/akovardin/pong/pongmobile Go package.
//   gobind -lang=objc github.com/akovardin/pong/pongmobile
//
// File is generated by gobind. Do not edit.

#ifndef __Pongmobile_H__
#define __Pongmobile_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


/**
 * Dummy is a dummy exported function.

gomobile doesn't compile a package that doesn't include any exported function.
Dummy forces gomobile to compile this package.
 */
FOUNDATION_EXPORT void PongmobileDummy(void);

#endif
